checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 7.0.10
    tests:
        override:
            -
                command: phpunit --coverage-clover=build/logs/clover.xml
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover
